# Generated by Django 6.0.5 on 2026-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
    ]
