# Generated by Django 6.0.5 on 2026-05-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_category", "0002_category_description_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
