# Generated by Django 6.0.5 on 2026-06-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
