# Generated by Django 6.0.5 on 2026-05-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fit_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
