# Generated by Django 6.0.5 on 2026-05-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product', '0004_coupon_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fit_type',
        ),
    ]
