# Generated by Django 6.0.5 on 2026-06-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product', '0005_remove_product_fit_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
