# Generated by Django 6.0.5 on 2026-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_order", "0003_order_cancel_reason_order_return_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cancelled_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="return_requested_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
